/**
 * Bark Seed Data – 200+ Hand-Crafted Gruff-But-Caring Quips
 *
 * Organized by tag (topic). Each bark is ≤30 words, slightly insulting,
 * good-natured, and designed to fit the GrumpRolled personality.
 *
 * Note: This file is processed by seed_barks.sql to populate the database.
 */

export const BARKS_BY_TAG = {
  default: [
    "Listen up, rookie – you just tripped over your own logic.",
    "That question has more red flags than a Soviet parade.",
    "You're about as subtle as a wrecking ball in a library.",
    "Your confusion is noted; now let's fix it.",
    "You're asking the right questions, even if your approach stinks.",
    "That's the kind of thinking that makes debugging a nightmare.",
    "You're not wrong, but your reasoning is about as solid as wet cardboard.",
    "Let me stop you right there before you implode something.",
    "You've got potential, kiddo – now develop some discipline.",
    "That idea has merit, but execution is the hard part.",
    "You're thinking too hard about the wrong thing.",
    "Your instinct is off, but your effort is noted.",
    "That's a rookie move, but we've all been there.",
    "You're barking up the wrong tree, but at least you're barking.",
    "Listen, your heart's in the right place, but your brain isn't.",
    "That's the kind of question that separates the pros from the amateurs.",
    "You're overthinking it like you overthink everything.",
    "Your approach is messier than a toddler's art project.",
    "That setup screams trouble from a mile away.",
    "You've got ambition; now get some smarts to match it.",
  ],

  code: [
    "Your function is about as clean as a mud-run in a hurricane.",
    "That code looks like it was written by a caffeinated squirrel.",
    "You're debugging like you're playing blindfolded poker.",
    "Your variable names are about as meaningful as alphabet soup.",
    "That loop will run longer than a bad marriage.",
    'Your error handling is basically "hope it doesn\'t break."',
    "That's the kind of hack that keeps engineers awake at night.",
    "Your code quality is directly proportional to your caffeine intake.",
    "You've got a syntax error and a philosophy problem.",
    "That coupling is tighter than a drum – untangle it.",
    "Your abstraction is so leaky it could fill a bathtub.",
    "That refactor is overdue, like your library books.",
    "Your test coverage has more holes than Swiss cheese.",
    "You're reinventing the wheel out of stubbornness.",
    "That class has more responsibilities than a flight attendant.",
    "Your naming convention is criminal.",
    "That's the kind of spaghetti code that gives DevOps nightmares.",
    "You're caching like you've never heard of cache invalidation.",
    "Your recursion is about to hit the stack limit.",
    "That side effect is sneakier than a cat burglar.",
  ],

  'ai-llm': [
    "Your prompt is about as precise as throwing darts blindfolded.",
    "You're treating the LLM like a magic 8-ball.",
    "That token budget is tighter than your deadline.",
    "Your fine-tuning strategy screams overfitting.",
    "You're hallucinating more than the model itself.",
    "That embedding space is more tangled than headphone cables.",
    "Your context window is about to overflow like a broken dam.",
    "You're using a sledgehammer to crack a nut.",
    "That temperature setting is hotter than a blast furnace.",
    "Your attention mechanism is paying zero attention.",
    "You're treating transformers like you understand them.",
    "That RAG setup has more moving parts than a Swiss watch.",
    "Your prompt engineering is more trial than error.",
    "You're stacking models like you're building a house of cards.",
    "That inference latency is worse than dial-up internet.",
    "Your model is more confused than the average user.",
    "You're quantizing like you're trying to lose quality.",
    "That loss function has plateau-d harder than a lazy hiker.",
    "Your sampling strategy needs a strategy of its own.",
    "You're treating this like it's not deeply non-trivial.",
  ],

  ops: [
    "Deploying that without testing? That's like sending a cat into a combat zone.",
    "Your infrastructure is more fragile than a glass house.",
    "That database migration is a ticking time bomb.",
    "Your monitoring is about as useful as a screen door on a submarine.",
    "You're orchestrating chaos like it's Kubernetes.",
    "That load balancer has given up on life.",
    'Your scaling strategy is "pray harder."',
    "That configuration is tangled like your headphone cord.",
    "You're managing secrets like you left them on a post-it.",
    'Your backup strategy is "hope nothing breaks."',
    "That firewall rule is a security nightmare.",
    "You're troubleshooting like you're blindfolded in the dark.",
    "Your logging is so quiet you'd miss an earthquake.",
    "That service mesh is more of a service mess.",
    "You're containerizing everything like it's a religion.",
    'Your disaster recovery plan is basically "panic."',
    "That latency is worse than a snail on vacation.",
    "You're running on smoke and mirrors, literally.",
    "Your deployment pipeline has more manual steps than a dance routine.",
    "That certificate expires sooner than your patience.",
  ],

  agents: [
    "Your agent is more stubborn than a mule.",
    "That task decomposition screams overcomplexity.",
    "You're treating autonomy like it's automatic.",
    "Your tool calls are leaving trails like breadcrumbs.",
    "That agentic loop is tighter than a noose.",
    "You're orchestrating agents like they're mind-reading.",
    "Your state management is a hot mess.",
    "That handoff between agents is messier than a relay race drop.",
    "You're assuming determinism where there's chaos.",
    "Your reward signal is noisier than a rock concert.",
    "That agent capability is more theoretical than practical.",
    "You're coordinating like nobody's talking to anybody.",
    "Your fallback strategy doesn't exist.",
    "That MCP setup is less coordinated than a toddler's drawing.",
    "You're treating agent memory like it's permanent.",
    'Your error handling is "just try again."',
    "That delegation is happening in a vacuum.",
    "You're scaling agents without testing single-agent sanity.",
    "Your agent monitoring is basically nonexistent.",
    "That task routing is about as smart as a coin flip.",
  ],

  forum: [
    "Your question was answered before you finished asking it.",
    "That grump is more confusing than the problem itself.",
    "You're debating like you didn't read the context.",
    "Your reply misses the point by three timezones.",
    "That take is spicier than your technical chops.",
    "You're voting on signal-to-noise, not signal.",
    "Your reputation score is about to take a hit.",
    "That post history screams inconsistency.",
    "You're searching the forum like you're looking for a lie.",
    "Your thread necromancy is poorly timed.",
    "That solution won't generalize beyond your case.",
    "You're assuming the community knows what you know.",
    "Your contribution is half-baked.",
    "That disagreement is based on vibes, not facts.",
    "You're tagging like you've never used categories.",
    "Your edit history reads like a confession.",
    "That feedback is more ego than insight.",
    "You're forum-sliding into unrelated territory.",
    "Your cross-post is spamming the same question everywhere.",
    "That moderation flag is overdue.",
  ],

  reasoning: [
    "Your logic has a short circuit somewhere.",
    "That deduction is about as solid as a house of cards.",
    "You're confusing correlation with causation, spectacularly.",
    "Your syllogism has a fatal flaw.",
    "That induction needs way more evidence.",
    "You're making leaps that would impress an Olympic gymnast.",
    "Your proof by contradiction just contradicted itself.",
    "That assumption is larger than the problem.",
    "You're reasoning in circles like you're hypnotized.",
    "Your cognitive bias is showing.",
    "That argument from authority is baseless.",
    "You're using anecdotes like they're data.",
    "Your false dichotomy is leaving out the obvious.",
    "That straw man just got flattened.",
    "You're moving goalposts like it's a sport.",
    "Your ad hominem is louder than your logic.",
    "That begging the question is circular, obviously.",
    "You're red herringing like you're fishing.",
    "Your slippery slope is missing the steps.",
    "That appeal to tradition ignores everything modern.",
  ],

  math: [
    "Your equation is more unbalanced than your diet.",
    "That calculation has decimal points in weird places.",
    "You're rounding like precision is optional.",
    "Your matrix is singular – handle it.",
    "That derivative is about to cross zero.",
    "You're integrating like you've never seen a limit.",
    "Your vector math is vectoring in the wrong direction.",
    "That probability model assumes a lot of innocence.",
    "You're extrapolating further than data allows.",
    "Your assumption of normality is laughably naive.",
    "That statistical significance is borderline fiction.",
    "You're using Occam's Razor but cutting off the important parts.",
    "Your Big O notation is off by several magnitudes.",
    "That combinatorial explosion is about to blow up.",
    "You're treating infinity like it's manageable.",
    "Your regression line assumes things aren't weird.",
    "That confidence interval is wider than the problem.",
    "You're approximating like you're blindfolded.",
    "Your numerical stability is about to collapse.",
    "That optimization is local, not global.",
  ],

  creative: [
    "That design is more confusing than helpful.",
    "Your UI has more friction than a rough surface.",
    "That aesthetic choice is... bold, let's say.",
    "You're optimizing for beauty over function.",
    'Your color palette screams "amateur hour."',
    "That layout has more wasted space than a McMansion.",
    "You're using whitespace like it owes you something.",
    "Your typography is harder to read than cursive.",
    "That animation is jankier than a rusted hinge.",
    "You're designing for your laptop, not humans.",
    "Your accessibility is an afterthought.",
    "That hierarchy is non-existent.",
    "You're using trendy like it's timeless.",
    "Your mobile responsiveness is... creatively broken.",
    "That hover state surprised absolutely nobody.",
    "You're treating dark mode like it's a theme park.",
    "Your vector work is more bloated than necessary.",
    "That inconsistency across screens is suspicious.",
    "You're loading images like bandwidth is infinite.",
    "Your UX copy is more confusing than helpful.",
  ],

  governance: [
    "Your compliance checklist is more wishful than factual.",
    "That audit trail has more gaps than Swiss cheese.",
    "You're treating this like GDPR is optional.",
    "Your access controls are as permissive as they come.",
    "That policy is more aspirational than enforced.",
    "You're documenting faster than you're thinking.",
    "Your risk assessment is optimistic fiction.",
    "That security review was skipped entirely.",
    "You're handling secrets like they're not secrets.",
    'Your data retention is "forever," apparently.',
    "That approval process doesn't exist.",
    "You're trusting user input like naively.",
    "Your encryption key management is terrifying.",
    "That change management process is: change happens.",
    "You're assuming no one will exploit this.",
    'Your incident response plan is "panic quietly."',
    "That vendor assessment was barely an assessment.",
    "You're treating security debt like it's not debt.",
    "Your third-party risk evaluation is missing.",
    "That compliance deadline just whooshed past.",
  ],
};

/**
 * Flatten all barks into a single format for seeding
 */
export function getAllBarks() {
  const all: Array<{ text: string; tag: string; mood: string; difficulty: number }> = [];

  for (const [tag, quips] of Object.entries(BARKS_BY_TAG)) {
    for (const text of quips) {
      all.push({
        text,
        tag,
        mood: 'gruff', // All these are gruff; adjust later if you want variety
        difficulty: Math.floor(Math.random() * 3) + 2, // 2-4 scale
      });
    }
  }

  return all;
}

export default BARKS_BY_TAG;
