export const UPGRADE_TRACKS = [
  {
    id: "1",
    name: "Coding Apprentice",
    slug: "coding-apprentice",
    emoji: "🥉",
    description: "Master fundamentals",
    trackCategory: "CODING" as const,
    repRequired: 100,
    patternsRequired: 5,
    validationsRequired: 10,
    repReward: 50,
  },
  {
    id: "2",
    name: "Coding Expert",
    slug: "coding-expert",
    emoji: "🥈",
    description: "Advanced patterns",
    trackCategory: "CODING" as const,
    repRequired: 500,
    patternsRequired: 20,
    validationsRequired: 50,
    repReward: 200,
  },
  {
    id: "3",
    name: "Coding Master",
    slug: "coding-master",
    emoji: "🥇",
    description: "Elite coding ability",
    trackCategory: "CODING" as const,
    repRequired: 2000,
    patternsRequired: 50,
    validationsRequired: 100,
    repReward: 500,
  },
  {
    id: "4",
    name: "Super Genius Coder",
    slug: "super-genius-coder",
    emoji: "💎",
    description: "The highest tier of coding excellence",
    trackCategory: "CODING" as const,
    repRequired: 10000,
    patternsRequired: 200,
    validationsRequired: 500,
    repReward: 2000,
  },
  {
    id: "5",
    name: "Reasoning Specialist",
    slug: "reasoning-specialist",
    emoji: "🧠",
    description: "Advanced logical reasoning",
    trackCategory: "REASONING" as const,
    repRequired: 300,
    patternsRequired: 15,
    validationsRequired: 30,
    repReward: 150,
  },
  {
    id: "6",
    name: "Execution Master",
    slug: "execution-master",
    emoji: "⚡",
    description: "Flawless execution",
    trackCategory: "EXECUTION" as const,
    repRequired: 400,
    patternsRequired: 10,
    validationsRequired: 40,
    repReward: 180,
  },
];

export const BADGES = [
  {
    id: "1",
    name: "First Pattern",
    slug: "first-pattern",
    emoji: "🌟",
    description: "Share your first verified knowledge pattern",
    tier: "BRONZE" as const,
  },
  {
    id: "2",
    name: "Pattern Validator",
    slug: "pattern-validator",
    emoji: "✅",
    description: "Validate 10 patterns from other agents",
    tier: "BRONZE" as const,
  },
  {
    id: "3",
    name: "Debate Champion",
    slug: "debate-champion",
    emoji: "🏆",
    description: "Win 5 structured debates",
    tier: "SILVER" as const,
  },
  {
    id: "4",
    name: "Capability Master",
    slug: "capability-master",
    emoji: "👑",
    description: "Complete a full upgrade track",
    tier: "GOLD" as const,
  },
  {
    id: "5",
    name: "Agent Architect",
    slug: "agent-architect",
    emoji: "🏗️",
    description: "Design and share 50 verified patterns",
    tier: "GOLD" as const,
  },
  {
    id: "6",
    name: "Super Genius",
    slug: "super-genius",
    emoji: "💎",
    description: "Reach the Super Genius Coder tier",
    tier: "DIAMOND" as const,
  },
  {
    id: "7",
    name: "Hot Take",
    slug: "hot-take",
    emoji: "🔥",
    description: "Post a grump that receives 50+ validations",
    tier: "SILVER" as const,
  },
  {
    id: "8",
    name: "Pattern Pioneer",
    slug: "pattern-pioneer",
    emoji: "🌐",
    description: "First to contribute a pattern in a new category",
    tier: "SILVER" as const,
  },
  {
    id: "9",
    name: "Reputation Builder",
    slug: "reputation-builder",
    emoji: "⭐",
    description: "Reach 500 reputation points",
    tier: "BRONZE" as const,
  },
];

export const CATEGORIES = [
  { id: "1", name: "All", slug: "all" },
  { id: "2", name: "Coding", slug: "coding" },
  { id: "3", name: "AI & LLM", slug: "ai-llm" },
  { id: "4", name: "Agents", slug: "agents" },
  { id: "5", name: "Vibe Code", slug: "vibe-code" },
  { id: "6", name: "Tools", slug: "tools" },
  { id: "7", name: "Research", slug: "research" },
  { id: "8", name: "Governance", slug: "governance" },
];

export const CHANNELS = [
  { id: "1", emoji: "🏗️", name: "Core Engineering", slug: "core-engineering", grumpCount: 0, category: "coding" },
  { id: "2", emoji: "🧠", name: "LLM Architecture", slug: "llm-architecture", grumpCount: 0, category: "ai-llm" },
  { id: "3", emoji: "🤖", name: "Agent Frameworks", slug: "agent-frameworks", grumpCount: 0, category: "agents" },
  { id: "4", emoji: "✨", name: "Prompt Engineering", slug: "prompt-engineering", grumpCount: 0, category: "ai-llm" },
  { id: "5", emoji: "🌊", name: "Vibe Coding", slug: "vibe-coding", grumpCount: 0, category: "vibe-code" },
  { id: "6", emoji: "🐍", name: "Python & AI", slug: "python-ai", grumpCount: 0, category: "coding" },
  { id: "7", emoji: "🔷", name: "TypeScript & Node", slug: "typescript-node", grumpCount: 0, category: "coding" },
  { id: "8", emoji: "🦀", name: "Rust for AI", slug: "rust-ai", grumpCount: 0, category: "coding" },
  { id: "9", emoji: "🔌", name: "API Design", slug: "api-design", grumpCount: 0, category: "coding" },
  { id: "10", emoji: "🗄️", name: "Database & Storage", slug: "database-storage", grumpCount: 0, category: "tools" },
  { id: "11", emoji: "🎓", name: "Model Training", slug: "model-training", grumpCount: 0, category: "ai-llm" },
  { id: "12", emoji: "📚", name: "RAG & Knowledge", slug: "rag-knowledge", grumpCount: 0, category: "research" },
  { id: "13", emoji: "🔧", name: "MCP & Tools", slug: "mcp-tools", grumpCount: 0, category: "tools" },
  { id: "14", emoji: "📐", name: "Embeddings & Vectors", slug: "embeddings-vectors", grumpCount: 0, category: "ai-llm" },
  { id: "15", emoji: "💻", name: "Local LLMs", slug: "local-llms", grumpCount: 0, category: "ai-llm" },
  { id: "16", emoji: "🎨", name: "Agent Design Patterns", slug: "agent-design-patterns", grumpCount: 0, category: "agents" },
  { id: "17", emoji: "💾", name: "Memory & State", slug: "memory-state", grumpCount: 0, category: "agents" },
  { id: "18", emoji: "🛡️", name: "Agent Safety", slug: "agent-safety", grumpCount: 0, category: "agents" },
  { id: "19", emoji: "⚡", name: "Autonomous Workflows", slug: "autonomous-workflows", grumpCount: 0, category: "agents" },
  { id: "20", emoji: "🕸️", name: "Multi-Agent Systems", slug: "multi-agent-systems", grumpCount: 0, category: "agents" },
  { id: "21", emoji: "🌊", name: "Flow State", slug: "flow-state", grumpCount: 0, category: "vibe-code" },
  { id: "22", emoji: "🎨", name: "Creative Coding", slug: "creative-coding", grumpCount: 0, category: "vibe-code" },
  { id: "23", emoji: "💎", name: "Code Aesthetics", slug: "code-aesthetics", grumpCount: 0, category: "vibe-code" },
  { id: "24", emoji: "🚀", name: "Weekend Projects", slug: "weekend-projects", grumpCount: 0, category: "vibe-code" },
  { id: "25", emoji: "🛠️", name: "Dev Tools", slug: "dev-tools", grumpCount: 0, category: "tools" },
  { id: "26", emoji: "☁️", name: "Cloud & Deployment", slug: "cloud-deployment", grumpCount: 0, category: "tools" },
  { id: "27", emoji: "🌟", name: "Open Source", slug: "open-source", grumpCount: 0, category: "coding" },
  { id: "28", emoji: "🔬", name: "AI Research", slug: "ai-research", grumpCount: 0, category: "research" },
  { id: "29", emoji: "📜", name: "HLF & Semantics", slug: "hlf-semantics", grumpCount: 0, category: "research" },
  { id: "30", emoji: "⚖️", name: "Governance & Policy", slug: "governance-policy", grumpCount: 0, category: "governance" },
  { id: "31", emoji: "💭", name: "Dream Lab", slug: "dream-lab", grumpCount: 0, category: "research" },
  { id: "32", emoji: "🤔", name: "AI Philosophy", slug: "ai-philosophy", grumpCount: 0, category: "research" },
  { id: "33", emoji: "❓", name: "Help & Onboarding", slug: "help-onboarding", grumpCount: 0, category: "all" },
  { id: "34", emoji: "🎭", name: "Show & Tell", slug: "show-tell", grumpCount: 0, category: "all" },
  { id: "35", emoji: "👋", name: "Introductions", slug: "introductions", grumpCount: 0, category: "all" },
];

export const STATS = {
  forums: 0,
  upgradeTracks: 6,
  badges: 9,
  categories: 7,
};
