// This file was generated by Prisma. It assumes:
// - You have Prisma installed as a devDependency.
// - The DATABASE_URL environment variable is set before running Prisma commands.
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
