[CmdletBinding()]
param(
    [string]$Provider = 'Managed Postgres'
)

$ErrorActionPreference = 'Stop'

function Read-ValueOrDefault {
    param(
        [string]$Prompt,
        [string]$Default
    )

    $value = Read-Host "$Prompt [$Default]"
    if ([string]::IsNullOrWhiteSpace($value)) {
        return $Default
    }

    return $value.Trim()
}

function Assert-PostgresUrl {
    param(
        [string]$Value,
        [string]$Name
    )

    if ([string]::IsNullOrWhiteSpace($Value)) {
        throw "$Name is required."
    }

    $trimmed = $Value.Trim()
    if (-not ($trimmed.StartsWith('postgresql://') -or $trimmed.StartsWith('postgres://'))) {
        throw "$Name must start with postgresql:// or postgres://"
    }

    return $trimmed
}

function New-AdminKey {
    $bytes = New-Object byte[] 24
    [Security.Cryptography.RandomNumberGenerator]::Fill($bytes)
    return 'gr_admin_' + ([Convert]::ToHexString($bytes).ToLowerInvariant())
}

Write-Host "Preparing .env.postgres.local for $Provider ..."
Write-Host 'Paste connection strings from your managed provider dashboard. Nothing is sent through chat.'

$databaseUrl = Assert-PostgresUrl -Name 'DATABASE_URL' -Value (Read-Host 'DATABASE_URL')
$directUrlInput = Read-Host 'DIRECT_URL (press Enter to reuse DATABASE_URL)'
$directUrl = if ([string]::IsNullOrWhiteSpace($directUrlInput)) {
    $databaseUrl
} else {
    Assert-PostgresUrl -Name 'DIRECT_URL' -Value $directUrlInput
}

$baseUrl = Read-ValueOrDefault -Prompt 'Local app base URL for smoke tests' -Default 'http://localhost:4692'
$adminKey = New-AdminKey
$envPath = Join-Path (Get-Location) '.env.postgres.local'

$content = @(
    "# Generated by scripts/setup-postgres-managed.ps1 for $Provider",
    "DATABASE_URL=\"$databaseUrl\"",
    "DIRECT_URL=\"$directUrl\"",
    "ADMIN_API_KEY=\"$adminKey\"",
    "GRUMPROLLED_BASE_URL=\"$baseUrl\"",
    'DB_QUERY_LOG="false"'
) -join "`r`n"

Set-Content -Path $envPath -Value "$content`r`n" -Encoding UTF8

Write-Host ".env.postgres.local written to $envPath"
Write-Host 'Next steps:'
Write-Host '1. npm run postgres:readiness'
Write-Host '2. npm run db:pg:push'
Write-Host '3. npm run dev:pg'
Write-Host '4. npm run smoke:pg:core'