$ErrorActionPreference = 'Stop'

function Get-HighestPsqlPath {
    $root = 'C:\Program Files\PostgreSQL'
    if (-not (Test-Path $root)) {
        throw 'PostgreSQL installation root not found.'
    }

    $versions = Get-ChildItem $root -Directory |
        Where-Object { $_.Name -match '^\d+$' } |
        Sort-Object { [int]$_.Name } -Descending

    foreach ($version in $versions) {
        $candidate = Join-Path $version.FullName 'bin\psql.exe'
        if (Test-Path $candidate) {
            return $candidate
        }
    }

    throw 'No psql.exe found under the PostgreSQL installation directory.'
}

function Read-ValueOrDefault {
    param(
        [string]$Prompt,
        [string]$Default
    )

    $value = Read-Host "$Prompt [$Default]"
    if ([string]::IsNullOrWhiteSpace($value)) {
        return $Default
    }

    return $value.Trim()
}

function Convert-SecureStringToPlainText {
    param([Security.SecureString]$SecureString)

    $bstr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($SecureString)
    try {
        return [Runtime.InteropServices.Marshal]::PtrToStringBSTR($bstr)
    }
    finally {
        [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr)
    }
}

function Invoke-Psql {
    param(
        [string]$PsqlPath,
        [string]$Host,
        [string]$Port,
        [string]$User,
        [string]$Password,
        [string]$Database,
        [string]$Sql
    )

    $env:PGPASSWORD = $Password
    try {
        $output = & $PsqlPath -h $Host -p $Port -U $User -d $Database -t -A -v ON_ERROR_STOP=1 -w -c $Sql 2>&1
        $exitCode = $LASTEXITCODE
        return [PSCustomObject]@{
            ExitCode = $exitCode
            Output = ($output | Out-String).Trim()
        }
    }
    finally {
        Remove-Item Env:PGPASSWORD -ErrorAction SilentlyContinue
    }
}

function New-AdminKey {
    $bytes = New-Object byte[] 24
    [Security.Cryptography.RandomNumberGenerator]::Fill($bytes)
    return 'gr_admin_' + ([Convert]::ToHexString($bytes).ToLowerInvariant())
}

$psqlPath = Get-HighestPsqlPath
$host = Read-ValueOrDefault -Prompt 'Postgres host' -Default 'localhost'
$port = Read-ValueOrDefault -Prompt 'Postgres port' -Default '5434'
$user = Read-ValueOrDefault -Prompt 'Postgres superuser' -Default 'postgres'
$maintenanceDb = Read-ValueOrDefault -Prompt 'Maintenance database for connection test' -Default 'postgres'
$targetDb = Read-ValueOrDefault -Prompt 'Application database to create/use' -Default 'grumprolled'
$securePassword = Read-Host 'Postgres password' -AsSecureString
$password = Convert-SecureStringToPlainText -SecureString $securePassword

if ([string]::IsNullOrWhiteSpace($password)) {
    throw 'A PostgreSQL password is required.'
}

Write-Host "Testing PostgreSQL connection with $psqlPath ..."
$connectionTest = Invoke-Psql -PsqlPath $psqlPath -Host $host -Port $port -User $user -Password $password -Database $maintenanceDb -Sql 'select current_user, current_database();'
if ($connectionTest.ExitCode -ne 0) {
    throw "Connection test failed.`n$($connectionTest.Output)"
}

Write-Host 'Connection succeeded.'

$dbExists = Invoke-Psql -PsqlPath $psqlPath -Host $host -Port $port -User $user -Password $password -Database $maintenanceDb -Sql "select 1 from pg_database where datname = '$targetDb';"
if ($dbExists.ExitCode -ne 0) {
    throw "Could not check database existence.`n$($dbExists.Output)"
}

if ($dbExists.Output -ne '1') {
    Write-Host "Creating database $targetDb ..."
    $createDb = Invoke-Psql -PsqlPath $psqlPath -Host $host -Port $port -User $user -Password $password -Database $maintenanceDb -Sql "create database $targetDb;"
    if ($createDb.ExitCode -ne 0) {
        throw "Could not create database $targetDb.`n$($createDb.Output)"
    }
}

$encodedPassword = [Uri]::EscapeDataString($password)
$adminKey = New-AdminKey
$envPath = Join-Path (Get-Location) '.env.postgres.local'

$content = @(
    '# Generated by scripts/setup-postgres-local.ps1',
    "DATABASE_URL=\"postgresql://$user:$encodedPassword@$host:$port/$targetDb?schema=public&connection_limit=20\"",
    "DIRECT_URL=\"postgresql://$user:$encodedPassword@$host:$port/$targetDb?schema=public\"",
    "ADMIN_API_KEY=\"$adminKey\"",
    'GRUMPROLLED_BASE_URL="http://localhost:4692"',
    'DB_QUERY_LOG="false"'
) -join "`r`n"

Set-Content -Path $envPath -Value "$content`r`n" -Encoding UTF8

Write-Host ".env.postgres.local written to $envPath"
Write-Host 'Next steps:'
Write-Host '1. npm run postgres:readiness'
Write-Host '2. npm run db:pg:push'
Write-Host '3. npm run dev:pg'
Write-Host '4. npm run smoke:pg:core'