$ErrorActionPreference = 'Stop'

function Get-AvailablePort {
    param([int[]]$Candidates)

    foreach ($candidate in $Candidates) {
        try {
            $listener = [System.Net.Sockets.TcpListener]::new([System.Net.IPAddress]::Loopback, $candidate)
            $listener.Start()
            $listener.Stop()
            return [string]$candidate
        } catch {
            continue
        }
    }

    throw 'No available local port found for Docker Redis setup.'
}

function Set-OrAppendEnvValue {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][string]$Key,
        [Parameter(Mandatory = $true)][string]$Value
    )

    $lines = @()
    if (Test-Path $Path) {
        $lines = Get-Content -Path $Path
    }

    $updated = $false
    for ($i = 0; $i -lt $lines.Count; $i++) {
        if ($lines[$i] -match "^$Key=") {
            $lines[$i] = ($Key + '="' + $Value + '"')
            $updated = $true
        }
    }

    if (-not $updated) {
        $lines += ($Key + '="' + $Value + '"')
    }

    Set-Content -Path $Path -Value (($lines -join "`r`n") + "`r`n") -Encoding UTF8
}

$dockerCommand = Get-Command docker -ErrorAction SilentlyContinue
if (-not $dockerCommand) {
    throw 'Docker is not installed or not on PATH. Install Docker Desktop first, then rerun npm run redis:setup-docker.'
}

$composePath = Join-Path (Get-Location) 'docker-compose.redis.yml'
if (-not (Test-Path $composePath)) {
    throw "Compose file not found: $composePath"
}

$dockerEnvPath = Join-Path (Get-Location) '.env.redis.docker.local'
$envTargetPath = Join-Path (Get-Location) '.env.postgres.local'
if (-not (Test-Path $envTargetPath)) {
    $envTargetPath = Join-Path (Get-Location) '.env.local'
}

$redisPort = Get-AvailablePort -Candidates @(6379, 6380, 6381, 6382)
$dockerContent = @(
    '# Generated by scripts/setup-redis-docker.ps1',
    "REDIS_PORT=$redisPort"
) -join "`r`n"

Set-Content -Path $dockerEnvPath -Value "$dockerContent`r`n" -Encoding UTF8

$redisUrl = "redis://127.0.0.1:${redisPort}"
Set-OrAppendEnvValue -Path $envTargetPath -Key 'REDIS_URL' -Value $redisUrl

Write-Host ".env.redis.docker.local written to $dockerEnvPath"
Write-Host "Redis runtime written to $envTargetPath"

$existingRedisContainer = (& docker ps -a --filter name=^/grumprolled-redis$ --format '{{.ID}}' 2>$null)
if ($existingRedisContainer) {
    Write-Host 'Removing existing grumprolled-redis container so the Docker Redis runtime can be recreated cleanly ...'
    & docker rm -f grumprolled-redis | Out-Null
}

Write-Host 'Starting local Docker Redis 7 ...'
& docker compose --env-file .env.redis.docker.local -f docker-compose.redis.yml up -d
if ($LASTEXITCODE -ne 0) {
    throw 'docker compose up failed.'
}

Write-Host 'Waiting for local Docker Redis health ...'
$healthy = $false
for ($i = 0; $i -lt 30; $i++) {
    $status = (& docker inspect --format '{{if .State.Health}}{{.State.Health.Status}}{{else}}{{.State.Status}}{{end}}' grumprolled-redis 2>$null)
    if ($status -eq 'healthy' -or $status -eq 'running') {
        $healthy = $true
        break
    }
    Start-Sleep -Seconds 1
}

if (-not $healthy) {
    Write-Warning 'Local Docker Redis did not report healthy status before timeout. Continuing because REDIS_URL was still written.'
}

Write-Host 'Next steps:'
Write-Host '1. Restart the GrumpRolled dev server so the updated REDIS_URL is loaded.'
Write-Host '2. Start the worker with npx tsx scripts/worker.ts after Redis 7 is healthy.'
Write-Host '3. Check /api/v1/admin/runtime-status and /api/v1/admin/launch-readiness.'