$ErrorActionPreference = 'Stop'

function Convert-BytesToHex {
    param([byte[]]$Bytes)

    return ([System.BitConverter]::ToString($Bytes).Replace('-', '').ToLowerInvariant())
}

function New-AdminKey {
    $bytes = New-Object byte[] 24
    $rng = [Security.Cryptography.RandomNumberGenerator]::Create()
    $rng.GetBytes($bytes)
    $rng.Dispose()
    return 'gr_admin_' + (Convert-BytesToHex -Bytes $bytes)
}

function New-RandomSecret {
    param([int]$ByteCount = 24)

    $bytes = New-Object byte[] $ByteCount
    $rng = [Security.Cryptography.RandomNumberGenerator]::Create()
    $rng.GetBytes($bytes)
    $rng.Dispose()
    return (Convert-BytesToHex -Bytes $bytes)
}

function Get-AvailablePort {
    param([int[]]$Candidates)

    foreach ($candidate in $Candidates) {
        $existing = Get-NetTCPConnection -LocalPort $candidate -State Listen -ErrorAction SilentlyContinue
        if (-not $existing) {
            return [string]$candidate
        }
    }

    throw 'No available local port found for Docker Postgres setup.'
}

$dockerCommand = Get-Command docker -ErrorAction SilentlyContinue
if (-not $dockerCommand) {
    throw 'Docker is not installed or not on PATH. Install Docker Desktop first, then rerun npm run db:pg:setup-docker.'
}

$composePath = Join-Path (Get-Location) 'docker-compose.postgres.yml'
if (-not (Test-Path $composePath)) {
    throw "Compose file not found: $composePath"
}

$envPath = Join-Path (Get-Location) '.env.postgres.local'
$dockerEnvPath = Join-Path (Get-Location) '.env.postgres.docker.local'
$adminKey = New-AdminKey
$dbName = 'grumprolled'
$dbUser = 'grumprolled_local'
$dbPassword = New-RandomSecret
$dbPort = Get-AvailablePort -Candidates @(5434, 55432, 55433, 55434)

$dockerContent = @(
    '# Generated by scripts/setup-postgres-docker.ps1',
    "POSTGRES_DB=$dbName",
    "POSTGRES_USER=$dbUser",
    "POSTGRES_PASSWORD=$dbPassword",
    "POSTGRES_PORT=$dbPort"
) -join "`r`n"

Set-Content -Path $dockerEnvPath -Value "$dockerContent`r`n" -Encoding UTF8

$databaseUrl = "postgresql://${dbUser}:${dbPassword}@localhost:${dbPort}/${dbName}?schema=public&connection_limit=20"
$directUrl = "postgresql://${dbUser}:${dbPassword}@localhost:${dbPort}/${dbName}?schema=public"

$content = @(
    '# Generated by scripts/setup-postgres-docker.ps1',
    ('DATABASE_URL="' + $databaseUrl + '"'),
    ('DIRECT_URL="' + $directUrl + '"'),
    ('ADMIN_API_KEY="' + $adminKey + '"'),
    'GRUMPROLLED_BASE_URL="http://localhost:4692"',
    'DB_QUERY_LOG="false"'
) -join "`r`n"

Set-Content -Path $envPath -Value "$content`r`n" -Encoding UTF8

Write-Host ".env.postgres.local written to $envPath"
Write-Host ".env.postgres.docker.local written to $dockerEnvPath"
Write-Host 'Starting local Docker Postgres ...'
& docker compose --env-file .env.postgres.docker.local -f docker-compose.postgres.yml up -d
if ($LASTEXITCODE -ne 0) {
    throw 'docker compose up failed.'
}

Write-Host 'Waiting for local Docker Postgres health ...'
$healthy = $false
for ($i = 0; $i -lt 30; $i++) {
    $status = (& docker inspect --format '{{if .State.Health}}{{.State.Health.Status}}{{else}}{{.State.Status}}{{end}}' grumprolled-postgres 2>$null)
    if ($status -eq 'healthy' -or $status -eq 'running') {
        $healthy = $true
        break
    }
    Start-Sleep -Seconds 1
}

if (-not $healthy) {
    Write-Warning 'Local Docker Postgres did not report healthy status before timeout. Continuing with generated env files.'
} else {
    Write-Host 'Synchronizing generated password into the database role ...'
    $sql = 'ALTER USER "' + $dbUser + '" WITH PASSWORD ''' + $dbPassword + ''';'
    & docker exec grumprolled-postgres psql -U $dbUser -d $dbName -c $sql
    if ($LASTEXITCODE -ne 0) {
        Write-Warning 'Failed to synchronize PostgreSQL user password. Continuing because the local Docker stack uses trust auth for host connections.'
    }
}

Write-Host 'Next steps:'
Write-Host '1. npm run postgres:readiness'
Write-Host '2. npm run db:pg:push'
Write-Host '3. npm run dev:pg'
Write-Host '4. npm run smoke:pg:core'